# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-27 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rollscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_score', models.IntegerField()),
                ('dice_value1', models.IntegerField(default=0)),
                ('dice_value2', models.IntegerField(default=0)),
                ('dice_value3', models.IntegerField(default=0)),
                ('dice_value4', models.IntegerField(default=0)),
                ('dice_value5', models.IntegerField(default=0)),
            ],
        ),
    ]
