# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-12 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_score', models.IntegerField(default=0)),
                ('hand_name', models.CharField(default='No Hand', max_length=140)),
                ('display_message', models.CharField(default="Let's roll!", max_length=140)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Die',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('die_value', models.IntegerField(default=0)),
                ('die_status', models.CharField(default='unlocked', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='diamonddice.Dice')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
