# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-02 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamonddice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rollscore',
            name='dice_status1',
            field=models.CharField(default='unlocked', max_length=30),
        ),
        migrations.AddField(
            model_name='rollscore',
            name='dice_status2',
            field=models.CharField(default='unlocked', max_length=30),
        ),
        migrations.AddField(
            model_name='rollscore',
            name='dice_status3',
            field=models.CharField(default='unlocked', max_length=30),
        ),
        migrations.AddField(
            model_name='rollscore',
            name='dice_status4',
            field=models.CharField(default='unlocked', max_length=30),
        ),
        migrations.AddField(
            model_name='rollscore',
            name='dice_status5',
            field=models.CharField(default='unlocked', max_length=30),
        ),
    ]
