# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-03 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamonddice', '0002_auto_20171102_1552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rollscore',
            new_name='Dicehand',
        ),
    ]
