# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-13 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamonddice', '0002_dice_round_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='dice',
            name='token',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='dice',
            name='display_message',
            field=models.CharField(default='start', max_length=140),
        ),
    ]
