# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-04 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamonddice', '0003_auto_20171103_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicehand',
            name='dice_score',
            field=models.IntegerField(default=0),
        ),
    ]
