# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-05 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamonddice', '0004_auto_20171104_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicehand',
            name='display_message',
            field=models.CharField(default='It worked!', max_length=140),
        ),
    ]
