# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-16 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamonddice', '0004_dice_alldice_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='dice',
            name='player_score',
            field=models.IntegerField(default=0),
        ),
    ]
