# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-19 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamonddice', '0007_auto_20171119_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_status',
            field=models.CharField(default='locked', max_length=15),
        ),
    ]
