# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-01 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamonddice', '0009_dice_roll_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='dice',
            name='previous_roll_saved',
            field=models.CharField(default='No', max_length=5),
        ),
    ]
