# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-09 02:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamonddice', '0010_auto_20171108_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dice',
            name='dicehand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dice', to='diamonddice.Dicehand'),
        ),
    ]
